# Generated by Django 4.2 on 2025-06-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secret', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
