# Generated by Django 5.2.1 on 2025-05-13 02:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_token', models.CharField(help_text='Token de autenticación del usuario', max_length=255)),
                ('preference_id', models.CharField(blank=True, help_text='ID de la preferencia en Mercado Pago', max_length=255, null=True)),
                ('init_point', models.URLField(blank=True, help_text='URL para redirigir al usuario para el pago', null=True)),
                ('status', models.CharField(default='pending', help_text='Estado del pago', max_length=50)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total del pago', max_digits=10, null=True)),
                ('cart_data', models.JSONField(blank=True, help_text='Datos del carrito del usuario', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Solicitud de pago',
                'verbose_name_plural': 'Solicitudes de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(help_text='ID del pago en Mercado Pago', max_length=255)),
                ('topic', models.CharField(help_text='Tipo de notificación', max_length=50)),
                ('raw_data', models.JSONField(help_text='Datos completos de la notificación')),
                ('processed', models.BooleanField(default=False, help_text='Indica si la notificación ya fue procesada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de recepción')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payment_service.paymentrequest')),
            ],
            options={
                'verbose_name': 'Notificación de pago',
                'verbose_name_plural': 'Notificaciones de pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
