# Generated by Django 5.2.1 on 2025-05-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID del pago en Mercado Pago', max_length=255, null=True),
        ),
    ]
